name: a02 frdocs

on:
  schedule:
    - cron: '0 1/4 * * *'  # S'exécute toutes les 4 heures à partir de 1 heure.
  workflow_dispatch:  # Permet de lancer le script manuellement depuis l'onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une image Ubuntu

    steps:
    - name: Vérifier le code source
      uses: actions/checkout@v5

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Version de Python à utiliser

    - name: Installer les dépendances
      run: |
        pip install requests  # Installer requests
        # Ajouter d'autres dépendances si nécessaire

    - name: Exécuter le script
      run: |
        python ${GITHUB_WORKSPACE}/a02/frdocs.py

    - name: Gestion des modifications apportées
      run: |
        git config user.name "BG47510"
        # Utilisez l'adresse e-mail de non-réponse de GitHub pour préserver votre confidentialité.
        git config --global user.email "username@users.noreply.github.com"
        git add a02/frdics.m3u8 a02/bak/frdocs.bak
        git commit -m "Actualisation du token dans le frdocs.m3u8 et bak" || echo "Rien à committer"
        git push
