name: ip github

on:
  #schedule:
    #- cron: '18 */4 * * *'  # Actualise toutes les 4 heures
  workflow_dispatch:       # Permet le déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v4

      - name: Vérifier la localisation du serveur github
        run: |
          github_geo=$(curl https://geo-info.ftven.fr/ws/edgescape.json)
          github_ip=$(curl https://api.ipify.org)
          # echo "La géolocalisation de github est: $github_ip" > githubip.data
          echo "$(date --utc +%FT%T%Z) geo-info: $github_geo" >> githubip.data
          echo "$(date --utc +%FT%T%Z) ipify: $github_ip" >> githubip.data


      #- name: Vérifie l'adresse IP de github
       # run: |
       #   github_ip=$(curl https://api.ipify.org)
        #  echo "L'adresse IP de github est: $github_ip" > githubip.data        

      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation" # github.com/BG47510
          git push
