name: ip github

on:
  workflow_dispatch:       # Déclenchement manuel

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel d’extraction
        uses: actions/checkout@v5

      - name: Vérifier la localisation du serveur github
        run: |
          github_geo=$(curl https://geo-info.ftven.fr/ws/edgescape.json)
          github_ip=$(curl https://api.ipify.org)
          {
          echo "$(date --utc +%FT%T%Z) La géolocalisation de github est: $github_geo"
          echo "$(date --utc +%FT%T%Z) L'adresse IP de github est: $github_ip"
          } > githubip.data  # > écrase l'ancien contenu
          # >> pour ajouter dans le fichier sans effacer l'ancien contenu.



      - name: Valider et envoyer les modifications
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          ls -la 
          git commit -m "Dernière actualisation" # github.com/BG47510
          git push
